apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: manish-notes
  description: Openshift Notes
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: CNCF
